# Notebook title

description here

### Import Libraries

fill this out later

In [1]:
import time
import requests
import pandas as pd
import numpy as np
from nba_api.stats.endpoints import scheduleleaguev2

pd.set_option('display.max_columns', None)

SEASON = "2025-26"
REQUEST_DELAY_SECONDS = 0.25
BASE_URL = "https://external-api.kalshi.com/trade-api/v2"
DATA = "../data/2025_raw_box_score_stats.csv"

### Consolidate games 

fill this out later

In [2]:
def game_consolidation(season_data):
    '''
    Fill this out later
    '''
    df = pd.read_csv(season_data)
    df = df.drop(columns=[
                "TEAM_ID", "SEASON_ID", "FGM", "FGA", "FG_PCT", "FG3M", "FG3A", "FG3_PCT",
                "FTM", "FTA", "FT_PCT", "OREB", "DREB", "REB", "AST", "STL", "BLK", "TOV", "PF", "PLUS_MINUS"
            ])

    home = df[df["MATCHUP"].str.contains("vs.")]
    away = df[df["MATCHUP"].str.contains("@")]
    games = home.merge(away, on="GAME_ID", suffixes=("_HOME", "_AWAY"))
    games = games.rename(columns={"MATCHUP_AWAY": 'MATCHUP'})
    games['WINNER'] = np.where(games['WL_HOME'] == "W", games['TEAM_NAME_HOME'], games['TEAM_NAME_AWAY'])

    games = games[[
            "GAME_ID", "GAME_DATE_HOME", "MATCHUP", 
            "TEAM_ABBREVIATION_AWAY", "TEAM_NAME_AWAY", "PTS_AWAY",
            "TEAM_ABBREVIATION_HOME", "TEAM_NAME_HOME", "PTS_HOME", "WINNER"
        ]]

    return games


test = game_consolidation(DATA)
test

,GAME_ID,GAME_DATE_HOME,MATCHUP,TEAM_ABBREVIATION_AWAY,TEAM_NAME_AWAY,PTS_AWAY,TEAM_ABBREVIATION_HOME,TEAM_NAME_HOME,PTS_HOME,WINNER
0,22500001,2025-10-21,HOU @ OKC,HOU,Houston Rockets,124,OKC,Oklahoma City Thunder,125,Oklahoma City Thunder
1,22500002,2025-10-21,GSW @ LAL,GSW,Golden State Warriors,119,LAL,Los Angeles Lakers,109,Golden State Warriors
2,22500086,2025-10-22,WAS @ MIL,WAS,Washington Wizards,120,MIL,Milwaukee Bucks,133,Milwaukee Bucks
3,22500003,2025-10-22,CLE @ NYK,CLE,Cleveland Cavaliers,111,NYK,New York Knicks,119,New York Knicks
4,22500081,2025-10-22,MIA @ ORL,MIA,Miami Heat,121,ORL,Orlando Magic,125,Orlando Magic
...,...,...,...,...,...,...,...,...,...,...
1220,22501194,2026-04-12,MEM @ HOU,MEM,Memphis Grizzlies,101,HOU,Houston Rockets,132,Houston Rockets
1221,22501199,2026-04-12,GSW @ LAC,GSW,Golden State Warriors,110,LAC,LA Clippers,115,LA Clippers
1222,22501198,2026-04-12,UTA @ LAL,UTA,Utah Jazz,107,LAL,Los Angeles Lakers,131,Los Angeles Lakers
1223,22501189,2026-04-12,ATL @ MIA,ATL,Atlanta Hawks,117,MIA,Miami Heat,143,Miami Heat
1224,22501192,2026-04-12,BKN @ TOR,BKN,Brooklyn Nets,101,TOR,Toronto Raptors,136,Toronto Raptors

### Get the game start times

fill this out later

In [3]:
def nba_game_start_times(year):
    '''
    Fill this out later
    '''
    sched = scheduleleaguev2.ScheduleLeagueV2(season=year)
    df = sched.season_games.get_data_frame()

    df = df[["gameId", "gameDate", "gameDateTimeUTC","gameDateTimeEst",
            "gameStatusText", "homeTeam_teamTricode", "awayTeam_teamTricode", "gameLabel"]]

    df = df.rename(columns={"gameId": 'GAME_ID'})
    df["GAME_ID"] = pd.to_numeric(df["GAME_ID"], errors="coerce").astype("Int64")
    games_to_keep = ['', 'Emirates NBA Cup', 'NBA Mexico City Game', 'NBA Berlin Game', 'NBA London Game', 'AWS NBA Rivals Week','NBA Pioneers Classic']
    df_filtered = df.loc[df['gameLabel'].isin(games_to_keep)]

    return df_filtered

test2 = nba_game_start_times(SEASON)
test2

,GAME_ID,gameDate,gameDateTimeUTC,gameDateTimeEst,gameStatusText,homeTeam_teamTricode,awayTeam_teamTricode,gameLabel
71,22500001,10/21/2025 00:00:00,2025-10-21T23:30:00Z,2025-10-21T19:30:00Z,Final/OT2,OKC,HOU,
72,22500002,10/21/2025 00:00:00,2025-10-22T02:00:00Z,2025-10-21T22:00:00Z,Final,LAL,GSW,
73,22500003,10/22/2025 00:00:00,2025-10-22T23:00:00Z,2025-10-22T19:00:00Z,Final,NYK,CLE,
74,22500004,10/22/2025 00:00:00,2025-10-23T01:30:00Z,2025-10-22T21:30:00Z,Final,DAL,SAS,
75,22500080,10/22/2025 00:00:00,2025-10-22T23:00:00Z,2025-10-22T19:00:00Z,Final,CHA,BKN,
...,...,...,...,...,...,...,...,...
1304,22501196,04/12/2026 00:00:00,2026-04-13T00:30:00Z,2026-04-12T20:30:00Z,Final,OKC,PHX,
1305,22501197,04/12/2026 00:00:00,2026-04-13T00:30:00Z,2026-04-12T20:30:00Z,Final,SAS,DEN,
1306,22501198,04/12/2026 00:00:00,2026-04-13T00:30:00Z,2026-04-12T20:30:00Z,Final,LAL,UTA,
1307,22501199,04/12/2026 00:00:00,2026-04-13T00:30:00Z,2026-04-12T20:30:00Z,Final,LAC,GSW,
1308,22501200,04/12/2026 00:00:00,2026-04-13T00:30:00Z,2026-04-12T20:30:00Z,Final,POR,SAC,

### Merge DF's and create columns with Kalshi info

fill this out later

In [4]:

def games_with_kalshi_info_converter(df1, df2):
    '''
    Fill this out later
    '''
    # merge the two dfs on GAME_ID using inner
    merged = pd.merge(df1, df2, on="GAME_ID", how="inner")
    
    # rename columns for clarity
    merged = merged.rename(columns={
        "GAME_DATE_HOME": "GAME_DATE",
        "TEAM_ABBREVIATION_AWAY": "ABBR_AWAY",
        "TEAM_NAME_AWAY": "NAME_AWAY",
        "TEAM_ABBREVIATION_HOME": "ABBR_HOME",
        "TEAM_NAME_HOME": "NAME_HOME",
        "gameStatusText": "STATUS"
    })

    # convert gameDateTimeEst column from object to datetieme
    merged["gameDateTimeEst"] = pd.to_datetime(merged["gameDateTimeEst"])

    # convert object columns to strings
    merged["ABBR_AWAY"] = merged["ABBR_AWAY"].astype(str)
    merged["ABBR_HOME"] = merged["ABBR_HOME"].astype(str)

    # create new column for clarity using 12 hour clock
    merged["GAME_START(EST)"] = (merged["gameDateTimeEst"].dt.strftime("%I:%M%p").str.lstrip("0"))

    # create Kalshi market ID's for away teams
    merged['KALSHI_ID_AWAY'] = ('KXNBAGAME-' +
        merged['gameDateTimeEst'].dt.strftime('%y') +
        merged['gameDateTimeEst'].dt.strftime('%b').str.upper() +
        merged['gameDateTimeEst'].dt.strftime('%d') + 
        merged['ABBR_AWAY'] +
        merged['ABBR_HOME'] + '-' +
        merged['ABBR_AWAY']
    )

    # create Kalshi market ID's for home teams
    merged['KALSHI_ID_HOME'] = ('KXNBAGAME-' + 
        merged['gameDateTimeEst'].dt.strftime('%y') +
        merged['gameDateTimeEst'].dt.strftime('%b').str.upper() +
        merged['gameDateTimeEst'].dt.strftime('%d') + 
        merged['ABBR_AWAY'] +
        merged['ABBR_HOME'] + '-' +
        merged['ABBR_HOME']
    )

    # create a timestamp column that will be used for fetching Kalshi data later
    merged['TIMESTAMP'] = (merged['gameDateTimeEst'].astype('int64') // 1_000_000_000)

    # reorganize final column order
    merged = merged[[
        "GAME_ID", "GAME_DATE", "GAME_START(EST)", "TIMESTAMP", 
        "KALSHI_ID_AWAY", "KALSHI_ID_HOME", "MATCHUP", 
        "ABBR_AWAY", "NAME_AWAY", "PTS_AWAY", 
        "ABBR_HOME", "NAME_HOME", "PTS_HOME",
        "WINNER", "STATUS"
    ]]

    return merged


test3 = games_with_kalshi_info_converter(test, test2)
test3

,GAME_ID,GAME_DATE,GAME_START(EST),TIMESTAMP,KALSHI_ID_AWAY,KALSHI_ID_HOME,MATCHUP,ABBR_AWAY,NAME_AWAY,PTS_AWAY,ABBR_HOME,NAME_HOME,PTS_HOME,WINNER,STATUS
0,22500001,2025-10-21,7:30PM,1761075000,KXNBAGAME-25OCT21HOUOKC-HOU,KXNBAGAME-25OCT21HOUOKC-OKC,HOU @ OKC,HOU,Houston Rockets,124,OKC,Oklahoma City Thunder,125,Oklahoma City Thunder,Final/OT2
1,22500002,2025-10-21,10:00PM,1761084000,KXNBAGAME-25OCT21GSWLAL-GSW,KXNBAGAME-25OCT21GSWLAL-LAL,GSW @ LAL,GSW,Golden State Warriors,119,LAL,Los Angeles Lakers,109,Golden State Warriors,Final
2,22500086,2025-10-22,8:00PM,1761163200,KXNBAGAME-25OCT22WASMIL-WAS,KXNBAGAME-25OCT22WASMIL-MIL,WAS @ MIL,WAS,Washington Wizards,120,MIL,Milwaukee Bucks,133,Milwaukee Bucks,Final
3,22500003,2025-10-22,7:00PM,1761159600,KXNBAGAME-25OCT22CLENYK-CLE,KXNBAGAME-25OCT22CLENYK-NYK,CLE @ NYK,CLE,Cleveland Cavaliers,111,NYK,New York Knicks,119,New York Knicks,Final
4,22500081,2025-10-22,7:00PM,1761159600,KXNBAGAME-25OCT22MIAORL-MIA,KXNBAGAME-25OCT22MIAORL-ORL,MIA @ ORL,MIA,Miami Heat,121,ORL,Orlando Magic,125,Orlando Magic,Final
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1220,22501194,2026-04-12,8:30PM,1776025800,KXNBAGAME-26APR12MEMHOU-MEM,KXNBAGAME-26APR12MEMHOU-HOU,MEM @ HOU,MEM,Memphis Grizzlies,101,HOU,Houston Rockets,132,Houston Rockets,Final
1221,22501199,2026-04-12,8:30PM,1776025800,KXNBAGAME-26APR12GSWLAC-GSW,KXNBAGAME-26APR12GSWLAC-LAC,GSW @ LAC,GSW,Golden State Warriors,110,LAC,LA Clippers,115,LA Clippers,Final
1222,22501198,2026-04-12,8:30PM,1776025800,KXNBAGAME-26APR12UTALAL-UTA,KXNBAGAME-26APR12UTALAL-LAL,UTA @ LAL,UTA,Utah Jazz,107,LAL,Los Angeles Lakers,131,Los Angeles Lakers,Final
1223,22501189,2026-04-12,6:00PM,1776016800,KXNBAGAME-26APR12ATLMIA-ATL,KXNBAGAME-26APR12ATLMIA-MIA,ATL @ MIA,ATL,Atlanta Hawks,117,MIA,Miami Heat,143,Miami Heat,Final
1224,22501192,2026-04-12,6:00PM,1776016800,KXNBAGAME-26APR12BKNTOR-BKN,KXNBAGAME-26APR12BKNTOR-TOR,BKN @ TOR,BKN,Brooklyn Nets,101,TOR,Toronto Raptors,136,Toronto Raptors,Final

In [ ]:
test3.to_csv("../data/_main(all-games).csv", index=False)

In [9]:
game_dict = dict(zip(test3['KALSHI_ID_AWAY'], test3['TIMESTAMP'])) | dict(zip(test3['KALSHI_ID_HOME'], test3['TIMESTAMP']))
#game_dict

### Kalshi Pre Game Data Fetch

fill this out later

In [6]:
def fetch_kalshi_candlesticks(ticker, end_ts, period_interval=60):
    """
    Use this funciton to fetch historical candlestick data from the Kalshi API.

    PARAMETERS;
        - ticker (str): market ticker symbol ('KXNBAGAME-25OCT21GSWLAL-GSW')
        - end_ts (int): timestamp marking the ending of the desired period (start of the game)
        - period_interval (int): time period length of each candlestick in minutes (60=1hr candles, 1=1min candles)

    Returns; a DataFrame containing the candlestick data with the following columns (among others):
        - KALSHI_ID (str): the unique market identifier
        - TIMESTAMP (datetime): date and time of candlestick ending
        - end_period_ts (int): timestamp of the candle close
        - open_interest (str): number of contracts still open by end of the candlestick period
        - volume (str): number of contracts bought on the market during the candlestick period
        - price_close (float): price of the last trade during the candlestick period
        - price_high (float): highest trade price during the candlestick period
        - price_low (float): lowest trade price during the candlestick period
        - price_mean (float): volume weighted average price during the candlestick period
        - price_open (float): price of the first trade during the candlestick period
    """
    # collect one hour of data before game starts (and exclude previous hours candle)
    period_seconds = period_interval * 60
    start_ts = end_ts - period_seconds + 1

    # list that will collect candlestick dicts from every chunk
    all_candles = []

    # send http get requests to the historical candlesticks endpoint
    response = requests.get(
        f"{BASE_URL}/historical/markets/{ticker}/candlesticks",
        params={'start_ts': start_ts, 'end_ts': end_ts, 'period_interval': period_interval},
        timeout=10)

    # error handling for if the market doesn't exist (or ticker info is wrong), or any other error
    if response.status_code == 404:
        print(f"Market {ticker} not found (404) - skipping")
        return pd.DataFrame()
    response.raise_for_status()

    # parse the JSON response and append this chunk’s candles to our list
    all_candles.extend(response.json()['candlesticks'])

    # necessary pause between requests to avoid Kalshi API rate limits
    time.sleep(REQUEST_DELAY_SECONDS)

    # flatten the nested candle dicts into a table; nested keys joined sep
    df = pd.json_normalize(all_candles, sep='_')

    # add ticker and datetime columns 
    df.insert(0, 'KALSHI_ID', ticker)
    df.insert(1, 'TIMESTAMP', pd.to_datetime(df['end_period_ts'], unit='s', utc=True))

    # keep only the last-hour candle (one row per ticker)
    df = df.sort_values("end_period_ts").tail(1).reset_index(drop=True)

    # drop unnecessary columns
    df = df.drop(columns=[
        "price_previous", "yes_ask_close", "yes_ask_high", "yes_ask_low", 
        "yes_ask_open", "yes_bid_close", "yes_bid_high", "yes_bid_low", "yes_bid_open"
    ])

    # convert columns to float
    float_cols = [
        "open_interest", "volume", "price_close", "price_high",
        "price_low", "price_mean", "price_open",
    ]
    df[float_cols] = df[float_cols].apply(pd.to_numeric, errors="coerce").round(4)

    return df


def kalshi_price_df_generator(game_dict):
    '''
    fill this out later
    '''
    count = 0
    all_dfs = []
    for ticker, ts in game_dict.items():
        df = fetch_kalshi_candlesticks(ticker, ts)
        if df.empty:
            print(f"-> skipped {ticker}")
            continue
        count += 1
        print(f"-> row {count} || {ticker} done")
        all_dfs.append(df)

    combined = pd.concat(all_dfs, ignore_index=True)

    return combined

In [7]:
test4 = kalshi_price_df_generator(game_dict)
test4

-> row 1 || KXNBAGAME-25OCT21HOUOKC-HOU done
-> row 2 || KXNBAGAME-25OCT21GSWLAL-GSW done
-> row 3 || KXNBAGAME-25OCT22WASMIL-WAS done
-> row 4 || KXNBAGAME-25OCT22CLENYK-CLE done
-> row 5 || KXNBAGAME-25OCT22MIAORL-MIA done
-> row 6 || KXNBAGAME-25OCT22SACPHX-SAC done
-> row 7 || KXNBAGAME-25OCT22MINPOR-MIN done
-> row 8 || KXNBAGAME-25OCT22TORATL-TOR done
-> row 9 || KXNBAGAME-25OCT22PHIBOS-PHI done
-> row 10 || KXNBAGAME-25OCT22DETCHI-DET done
-> row 11 || KXNBAGAME-25OCT22SASDAL-SAS done
-> row 12 || KXNBAGAME-25OCT22LACUTA-LAC done
-> row 13 || KXNBAGAME-25OCT22NOPMEM-NOP done
-> row 14 || KXNBAGAME-25OCT22BKNCHA-BKN done
-> row 15 || KXNBAGAME-25OCT23OKCIND-OKC done
-> row 16 || KXNBAGAME-25OCT23DENGSW-DEN done
-> row 17 || KXNBAGAME-25OCT24CLEBKN-CLE done
-> row 18 || KXNBAGAME-25OCT24BOSNYK-BOS done
-> row 19 || KXNBAGAME-25OCT24ATLORL-ATL done
-> row 20 || KXNBAGAME-25OCT24GSWPOR-GSW done
-> row 21 || KXNBAGAME-25OCT24UTASAC-UTA done
-> row 22 || KXNBAGAME-25OCT24SASNOP-SAS done
-> row 23 || KXNBAGAME-25OCT24WASDAL-WAS done
-> row 24 || KXNBAGAME-25OCT24DETHOU-DET done
-> row 25 || KXNBAGAME-25OCT24PHXLAC-PHX done
-> row 26 || KXNBAGAME-25OCT24MINLAL-MIN done
-> row 27 || KXNBAGAME-25OCT24MILTOR-MIL done
-> row 28 || KXNBAGAME-25OCT24MIAMEM-MIA done
-> row 29 || KXNBAGAME-25OCT25CHIORL-CHI done
-> row 30 || KXNBAGAME-25OCT25CHAPHI-CHA done
-> row 31 || KXNBAGAME-25OCT25OKCATL-OKC done
-> row 32 || KXNBAGAME-25OCT25PHXDEN-PHX done
-> row 33 || KXNBAGAME-25OCT25INDMEM-IND done
-> row 34 || KXNBAGAME-25OCT26INDMIN-IND done
-> row 35 || KXNBAGAME-25OCT26LALSAC-LAL done
-> row 36 || KXNBAGAME-25OCT26BKNSAS-BKN done
-> row 37 || KXNBAGAME-25OCT26MILCLE-MIL done
-> row 38 || KXNBAGAME-25OCT26TORDAL-TOR done
-> row 39 || KXNBAGAME-25OCT26PORLAC-POR done
-> row 40 || KXNBAGAME-25OCT26NYKMIA-NYK done
-> row 41 || KXNBAGAME-25OCT26CHAWAS-CHA done
-> row 42 || KXNBAGAME-25OCT26BOSDET-BOS done
-> row 43 || KXNBAGAME-25OCT27DENMIN-DEN done
-> row 44 || KXNBAGAME-25OCT27ORLPHI-ORL done
-> row 45 || KXNBAGAME-25OCT27TORSAS-TOR done
-> row 46 || KXNBAGAME-25OCT27BOSNOP-BOS done
-> row 47 || KXNBAGAME-25OCT27ATLCHI-ATL done
-> row 48 || KXNBAGAME-25OCT27OKCDAL-OKC done
-> row 49 || KXNBAGAME-25OCT27MEMGSW-MEM done
-> row 50 || KXNBAGAME-25OCT27BKNHOU-BKN done
-> row 51 || KXNBAGAME-25OCT27PORLAL-POR done
-> row 52 || KXNBAGAME-25OCT27PHXUTA-PHX done
-> row 53 || KXNBAGAME-25OCT27CLEDET-CLE done
-> row 54 || KXNBAGAME-25OCT28NYKMIL-NYK done
-> row 55 || KXNBAGAME-25OCT28SACOKC-SAC done
-> row 56 || KXNBAGAME-25OCT28LACGSW-LAC done
-> row 57 || KXNBAGAME-25OCT28CHAMIA-CHA done
-> row 58 || KXNBAGAME-25OCT28PHIWAS-PHI done
-> row 59 || KXNBAGAME-25OCT29LALMIN-LAL done
-> row 60 || KXNBAGAME-25OCT29ATLBKN-ATL done
-> row 61 || KXNBAGAME-25OCT29MEMPHX-MEM done
-> row 62 || KXNBAGAME-25OCT29CLEBOS-CLE done
-> row 63 || KXNBAGAME-25OCT29SACCHI-SAC done
-> row 64 || KXNBAGAME-25OCT29INDDAL-IND done
-> row 65 || KXNBAGAME-25OCT29NOPDEN-NOP done
-> row 66 || KXNBAGAME-25OCT29HOUTOR-HOU done
-> row 67 || KXNBAGAME-25OCT29PORUTA-POR done
-> row 68 || KXNBAGAME-25OCT29ORLDET-ORL done
-> row 69 || KXNBAGAME-25OCT30GSWMIL-GSW done
-> row 70 || KXNBAGAME-25OCT30MIASAS-MIA done
-> row 71 || KXNBAGAME-25OCT30WASOKC-WAS done
-> row 72 || KXNBAGAME-25OCT30ORLCHA-ORL done
-> row 73 || KXNBAGAME-25OCT31ATLIND-ATL done
-> row 74 || KXNBAGAME-25OCT31BOSPHI-BOS done
-> row 75 || KXNBAGAME-25OCT31UTAPHX-UTA done
-> row 76 || KXNBAGAME-25OCT31DENPOR-DEN done
-> row 77 || KXNBAGAME-25OCT31TORCLE-TOR done
-> row 78 || KXNBAGAME-25OCT31NYKCHI-NYK done
-> row 79 || KXNBAGAME-25OCT31NOPLAC-NOP done
-> row 80 || KXNBAGAME-25OCT31LALMEM-LAL done
-> row 81 || KXNBAGAME-25NOV01SACMIL-SAC done
-> row 82 || KXNBAGAME-25NOV01GSWIND-GSW done
-> row 83 || KXNBAGAME-25NOV01HOUBOS-HOU done
-> row 84 || KXNBAGAME-25NOV01ORLWAS-ORL done
-> row 85 || KXNBAGAME-25NOV01MINCHA-MIN done
-> row 86 || KXNBAGAME-25NOV02PHIBKN-PHI done
-> row 87 || KXNBAGAME-25NOV02CHINYK-CHI done
-> row 88 || KXNBAGAME-25NOV02SASPHX-SAS done
-> row 89 || KXNBAGAME-25NOV02NOPOKC-NOP done
-> row 90 || KXNBAGAME-25NOV02ATLCLE-ATL done
-> row 91 || KXNBAGAME-25NOV02MIALAL-MIA done
-> row 92 || KXNBAGAME-25NOV02MEMTOR-MEM done
-> row 93 || KXNBAGAME-25NOV02UTACHA-UTA done
-> row 94 || KXNBAGAME-25NOV03MINBKN-MIN done
-> row 95 || KXNBAGAME-25NOV03WASNYK-WAS done
-> row 96 || KXNBAGAME-25NOV03MILIND-MIL done
-> row 97 || KXNBAGAME-25NOV03LALPOR-LAL done
-> row 98 || KXNBAGAME-25NOV03UTABOS-UTA done
-> row 99 || KXNBAGAME-25NOV03SACDEN-SAC done
-> row 100 || KXNBAGAME-25NOV03DALHOU-DAL done
-> row 101 || KXNBAGAME-25NOV03MIALAC-MIA done
-> row 102 || KXNBAGAME-25NOV03DETMEM-DET done
-> row 103 || KXNBAGAME-25NOV04ORLATL-ORL done
-> row 104 || KXNBAGAME-25NOV04CHANOP-CHA done
-> row 105 || KXNBAGAME-25NOV04PHICHI-PHI done
-> row 106 || KXNBAGAME-25NOV04PHXGSW-PHX done
-> row 107 || KXNBAGAME-25NOV04OKCLAC-OKC done
-> row 108 || KXNBAGAME-25NOV04MILTOR-MIL done
-> row 109 || KXNBAGAME-25NOV05MINNYK-MIN done
-> row 110 || KXNBAGAME-25NOV05BKNIND-BKN done
-> row 111 || KXNBAGAME-25NOV05OKCPOR-OKC done
-> row 112 || KXNBAGAME-25NOV05GSWSAC-GSW done
-> row 113 || KXNBAGAME-25NOV05WASBOS-WAS done
-> row 114 || KXNBAGAME-25NOV05PHICLE-PHI done
-> row 115 || KXNBAGAME-25NOV05NOPDAL-NOP done
-> row 116 || KXNBAGAME-25NOV05MIADEN-MIA done
-> row 117 || KXNBAGAME-25NOV05SASLAL-SAS done
-> row 118 || KXNBAGAME-25NOV05HOUMEM-HOU done
-> row 119 || KXNBAGAME-25NOV05UTADET-UTA done
-> row 120 || KXNBAGAME-25NOV06LACPHX-LAC done
-> row 121 || KXNBAGAME-25NOV07CHIMIL-CHI done
-> row 122 || KXNBAGAME-25NOV07UTAMIN-UTA done
-> row 123 || KXNBAGAME-25NOV07DETBKN-DET done
-> row 124 || KXNBAGAME-25NOV07BOSORL-BOS done
-> row 125 || KXNBAGAME-25NOV07OKCSAC-OKC done
-> row 126 || KXNBAGAME-25NOV07HOUSAS-HOU done
-> row 127 || KXNBAGAME-25NOV07TORATL-TOR done
-> row 128 || KXNBAGAME-25NOV07GSWDEN-GSW done
-> row 129 || KXNBAGAME-25NOV07CHAMIA-CHA done
-> row 130 || KXNBAGAME-25NOV07DALMEM-DAL done
-> row 131 || KXNBAGAME-25NOV07CLEWAS-CLE done
-> row 132 || KXNBAGAME-25NOV08TORPHI-TOR done
-> row 133 || KXNBAGAME-25NOV08NOPSAS-NOP done
-> row 134 || KXNBAGAME-25NOV08LALATL-LAL done
-> row 135 || KXNBAGAME-25NOV08CHICLE-CHI done
-> row 136 || KXNBAGAME-25NOV08INDDEN-IND done
-> row 137 || KXNBAGAME-25NOV08PHXLAC-PHX done
-> row 138 || KXNBAGAME-25NOV08PORMIA-POR done
-> row 139 || KXNBAGAME-25NOV08DALWAS-DAL done
-> row 140 || KXNBAGAME-25NOV09HOUMIL-HOU done
-> row 141 || KXNBAGAME-25NOV09BKNNYK-BKN done
-> row 142 || KXNBAGAME-25NOV09BOSORL-BOS done
-> row 143 || KXNBAGAME-25NOV09DETPHI-DET done
-> row 144 || KXNBAGAME-25NOV09MINSAC-MIN done
-> row 145 || KXNBAGAME-25NOV09INDGSW-IND done
-> row 146 || KXNBAGAME-25NOV09OKCMEM-OKC done
-> row 147 || KXNBAGAME-25NOV10PORORL-POR done
-> row 148 || KXNBAGAME-25NOV10NOPPHX-NOP done
-> row 149 || KXNBAGAME-25NOV10SASCHI-SAS done
-> row 150 || KXNBAGAME-25NOV10MILDAL-MIL done
-> row 151 || KXNBAGAME-25NOV10ATLLAC-ATL done
-> row 152 || KXNBAGAME-25NOV10CLEMIA-CLE done
-> row 153 || KXNBAGAME-25NOV10MINUTA-MIN done
-> row 154 || KXNBAGAME-25NOV10WASDET-WAS done
-> row 155 || KXNBAGAME-25NOV10LALCHA-LAL done
-> row 156 || KXNBAGAME-25NOV11TORBKN-TOR done
-> row 157 || KXNBAGAME-25NOV11MEMNYK-MEM done
-> row 158 || KXNBAGAME-25NOV11BOSPHI-BOS done
-> row 159 || KXNBAGAME-25NOV11DENSAC-DEN done
-> row 160 || KXNBAGAME-25NOV11GSWOKC-GSW done
-> row 161 || KXNBAGAME-25NOV11INDUTA-IND done
-> row 162 || KXNBAGAME-25NOV12ORLNYK-ORL done
-> row 163 || KXNBAGAME-25NOV12ATLSAC-ATL done
-> row 164 || KXNBAGAME-25NOV12GSWSAS-GSW done
-> row 165 || KXNBAGAME-25NOV12LALOKC-LAL done
-> row 166 || KXNBAGAME-25NOV12MEMBOS-MEM done
-> row 167 || KXNBAGAME-25NOV12PORNOP-POR done
-> row 168 || KXNBAGAME-25NOV12PHXDAL-PHX done
-> row 169 || KXNBAGAME-25NOV12WASHOU-WAS done
-> row 170 || KXNBAGAME-25NOV12DENLAC-DEN done
-> row 171 || KXNBAGAME-25NOV12CLEMIA-CLE done
-> row 172 || KXNBAGAME-25NOV12CHIDET-CHI done
-> row 173 || KXNBAGAME-25NOV12MILCHA-MIL done
-> row 174 || KXNBAGAME-25NOV13INDPHX-IND done
-> row 175 || KXNBAGAME-25NOV13TORCLE-TOR done
-> row 176 || KXNBAGAME-25NOV13ATLUTA-ATL done
-> row 177 || KXNBAGAME-25NOV14CHAMIL-CHA done
-> row 178 || KXNBAGAME-25NOV14SACMIN-SAC done
-> row 179 || KXNBAGAME-25NOV14MIANYK-MIA done
-> row 180 || KXNBAGAME-25NOV14BKNORL-BKN done
-> row 181 || KXNBAGAME-25NOV14GSWSAS-GSW done
-> row 182 || KXNBAGAME-25NOV14LALNOP-LAL done
-> row 183 || KXNBAGAME-25NOV14LACDAL-LAC done
-> row 184 || KXNBAGAME-25NOV14PORHOU-POR done
-> row 185 || KXNBAGAME-25NOV14PHIDET-PHI done
-> row 186 || KXNBAGAME-25NOV15LALMIL-LAL done
-> row 187 || KXNBAGAME-25NOV15DENMIN-DEN done
-> row 188 || KXNBAGAME-25NOV15TORIND-TOR done
-> row 189 || KXNBAGAME-25NOV15MEMCLE-MEM done
-> row 190 || KXNBAGAME-25NOV15OKCCHA-OKC done
-> row 191 || KXNBAGAME-25NOV16ATLPHX-ATL done
-> row 192 || KXNBAGAME-25NOV16SACSAS-SAC done
-> row 193 || KXNBAGAME-25NOV16LACBOS-LAC done
-> row 194 || KXNBAGAME-25NOV16GSWNOP-GSW done
-> row 195 || KXNBAGAME-25NOV16PORDAL-POR done
-> row 196 || KXNBAGAME-25NOV16ORLHOU-ORL done
-> row 197 || KXNBAGAME-25NOV16CHIUTA-CHI done
-> row 198 || KXNBAGAME-25NOV16BKNWAS-BKN done
-> row 199 || KXNBAGAME-25NOV17DALMIN-DAL done
-> row 200 || KXNBAGAME-25NOV17LACPHI-LAC done
-> row 201 || KXNBAGAME-25NOV17MILCLE-MIL done
-> row 202 || KXNBAGAME-25NOV17OKCNOP-OKC done
-> row 203 || KXNBAGAME-25NOV17CHIDEN-CHI done
-> row 204 || KXNBAGAME-25NOV17NYKMIA-NYK done
-> row 205 || KXNBAGAME-25NOV17CHATOR-CHA done
-> row 206 || KXNBAGAME-25NOV17INDDET-IND done
-> row 207 || KXNBAGAME-25NOV18BOSBKN-BOS done
-> row 208 || KXNBAGAME-25NOV18GSWORL-GSW done
-> row 209 || KXNBAGAME-25NOV18PHXPOR-PHX done
-> row 210 || KXNBAGAME-25NOV18MEMSAS-MEM done
-> row 211 || KXNBAGAME-25NOV18DETATL-DET done
-> row 212 || KXNBAGAME-25NOV18UTALAL-UTA done
-> row 213 || KXNBAGAME-25NOV19WASMIN-WAS done
-> row 214 || KXNBAGAME-25NOV19CHAIND-CHA done
-> row 215 || KXNBAGAME-25NOV19TORPHI-TOR done
-> row 216 || KXNBAGAME-25NOV19CHIPOR-CHI done
-> row 217 || KXNBAGAME-25NOV19SACOKC-SAC done
-> row 218 || KXNBAGAME-25NOV19HOUCLE-HOU done
-> row 219 || KXNBAGAME-25NOV19DENNOP-DEN done
-> row 220 || KXNBAGAME-25NOV19NYKDAL-NYK done
-> row 221 || KXNBAGAME-25NOV19GSWMIA-GSW done
-> row 222 || KXNBAGAME-25NOV20PHIMIL-PHI done
-> row 223 || KXNBAGAME-25NOV20LACORL-LAC done
-> row 224 || KXNBAGAME-25NOV20ATLSAS-ATL done
-> row 225 || KXNBAGAME-25NOV20SACMEM-SAC done
-> row 226 || KXNBAGAME-25NOV21MINPHX-MIN done
-> row 227 || KXNBAGAME-25NOV21BKNBOS-BKN done
-> row 228 || KXNBAGAME-25NOV21INDCLE-IND done
-> row 229 || KXNBAGAME-25NOV21MIACHI-MIA done
-> row 230 || KXNBAGAME-25NOV21NOPDAL-NOP done
-> row 231 || KXNBAGAME-25NOV21PORGSW-POR done
-> row 232 || KXNBAGAME-25NOV21DENHOU-DEN done
-> row 233 || KXNBAGAME-25NOV21WASTOR-WAS done
-> row 234 || KXNBAGAME-25NOV21OKCUTA-OKC done
-> row 235 || KXNBAGAME-25NOV22DETMIL-DET done
-> row 236 || KXNBAGAME-25NOV22NYKORL-NYK done
-> row 237 || KXNBAGAME-25NOV22ATLNOP-ATL done
-> row 238 || KXNBAGAME-25NOV22WASCHI-WAS done
-> row 239 || KXNBAGAME-25NOV22MEMDAL-MEM done
-> row 240 || KXNBAGAME-25NOV22SACDEN-SAC done
-> row 241 || KXNBAGAME-25NOV22LACCHA-LAC done
-> row 242 || KXNBAGAME-25NOV23MIAPHI-MIA done
-> row 243 || KXNBAGAME-25NOV23SASPHX-SAS done
-> row 244 || KXNBAGAME-25NOV23POROKC-POR done
-> row 245 || KXNBAGAME-25NOV23CHAATL-CHA done
-> row 246 || KXNBAGAME-25NOV23ORLBOS-ORL done
-> row 247 || KXNBAGAME-25NOV23LACCLE-LAC done
-> row 248 || KXNBAGAME-25NOV23BKNTOR-BKN done
-> row 249 || KXNBAGAME-25NOV23LALUTA-LAL done
-> row 250 || KXNBAGAME-25NOV24PORMIL-POR done
-> row 251 || KXNBAGAME-25NOV24NYKBKN-NYK done
-> row 252 || KXNBAGAME-25NOV24DETIND-DET done
-> row 253 || KXNBAGAME-25NOV24HOUPHX-HOU done
-> row 254 || KXNBAGAME-25NOV24MINSAC-MIN done
-> row 255 || KXNBAGAME-25NOV24CHINOP-CHI done
-> row 256 || KXNBAGAME-25NOV24UTAGSW-UTA done
-> row 257 || KXNBAGAME-25NOV24DALMIA-DAL done
-> row 258 || KXNBAGAME-25NOV24CLETOR-CLE done
-> row 259 || KXNBAGAME-25NOV24DENMEM-DEN done
-> row 260 || KXNBAGAME-25NOV25ORLPHI-ORL done
-> row 261 || KXNBAGAME-25NOV25LACLAL-LAC done
-> row 262 || KXNBAGAME-25NOV25ATLWAS-ATL done
-> row 263 || KXNBAGAME-25NOV26SASPOR-SAS done
-> row 264 || KXNBAGAME-25NOV26PHXSAC-PHX done
-> row 265 || KXNBAGAME-25NOV26MINOKC-MIN done
-> row 266 || KXNBAGAME-25NOV26DETBOS-DET done
-> row 267 || KXNBAGAME-25NOV26MEMNOP-MEM done
-> row 268 || KXNBAGAME-25NOV26HOUGSW-HOU done
-> row 269 || KXNBAGAME-25NOV26MILMIA-MIL done
-> row 270 || KXNBAGAME-25NOV26INDTOR-IND done
-> row 271 || KXNBAGAME-25NOV26NYKCHA-NYK done
-> row 272 || KXNBAGAME-25NOV28PHIBKN-PHI done
-> row 273 || KXNBAGAME-25NOV28MILNYK-MIL done
-> row 274 || KXNBAGAME-25NOV28WASIND-WAS done
-> row 275 || KXNBAGAME-25NOV28PHXOKC-PHX done
-> row 276 || KXNBAGAME-25NOV28CLEATL-CLE done
-> row 277 || KXNBAGAME-25NOV28SASDEN-SAS done
-> row 278 || KXNBAGAME-25NOV28MEMLAC-MEM done
-> row 279 || KXNBAGAME-25NOV28DALLAL-DAL done
-> row 280 || KXNBAGAME-25NOV28SACUTA-SAC done
-> row 281 || KXNBAGAME-25NOV28ORLDET-ORL done
-> row 282 || KXNBAGAME-25NOV28CHICHA-CHI done
-> row 283 || KXNBAGAME-25NOV29BKNMIL-BKN done
-> row 284 || KXNBAGAME-25NOV29BOSMIN-BOS done
-> row 285 || KXNBAGAME-25NOV29CHIIND-CHI done
-> row 286 || KXNBAGAME-25NOV29DENPHX-DEN done
-> row 287 || KXNBAGAME-25NOV29NOPGSW-NOP done
-> row 288 || KXNBAGAME-25NOV29DALLAC-DAL done
-> row 289 || KXNBAGAME-25NOV29DETMIA-DET done
-> row 290 || KXNBAGAME-25NOV29TORCHA-TOR done
-> row 291 || KXNBAGAME-25NOV30SASMIN-SAS done
-> row 292 || KXNBAGAME-25NOV30TORNYK-TOR done
-> row 293 || KXNBAGAME-25NOV30ATLPHI-ATL done
-> row 294 || KXNBAGAME-25NOV30OKCPOR-OKC done
-> row 295 || KXNBAGAME-25NOV30MEMSAC-MEM done
-> row 296 || KXNBAGAME-25NOV30BOSCLE-BOS done
-> row 297 || KXNBAGAME-25NOV30NOPLAL-NOP done
-> row 298 || KXNBAGAME-25NOV30HOUUTA-HOU done
-> row 299 || KXNBAGAME-25DEC01CHABKN-CHA done
-> row 300 || KXNBAGAME-25DEC01CHIORL-CHI done
-> row 301 || KXNBAGAME-25DEC01CLEIND-CLE done
-> row 302 || KXNBAGAME-25DEC01DALDEN-DAL done
-> row 303 || KXNBAGAME-25DEC01PHXLAL-PHX done
-> row 304 || KXNBAGAME-25DEC01LACMIA-LAC done
-> row 305 || KXNBAGAME-25DEC01HOUUTA-HOU done
-> row 306 || KXNBAGAME-25DEC01MILWAS-MIL done
-> row 307 || KXNBAGAME-25DEC01ATLDET-ATL done
-> row 308 || KXNBAGAME-25DEC02WASPHI-WAS done
-> row 309 || KXNBAGAME-25DEC02MEMSAS-MEM done
-> row 310 || KXNBAGAME-25DEC02NYKBOS-NYK done
-> row 311 || KXNBAGAME-25DEC02MINNOP-MIN done
-> row 312 || KXNBAGAME-25DEC02OKCGSW-OKC done
-> row 313 || KXNBAGAME-25DEC02PORTOR-POR done
-> row 314 || KXNBAGAME-25DEC03DETMIL-DET done
-> row 315 || KXNBAGAME-25DEC03CHANYK-CHA done
-> row 316 || KXNBAGAME-25DEC03SASORL-SAS done
-> row 317 || KXNBAGAME-25DEC03DENIND-DEN done
-> row 318 || KXNBAGAME-25DEC03LACATL-LAC done
-> row 319 || KXNBAGAME-25DEC03PORCLE-POR done
-> row 320 || KXNBAGAME-25DEC03BKNCHI-BKN done
-> row 321 || KXNBAGAME-25DEC03MIADAL-MIA done
-> row 322 || KXNBAGAME-25DEC03SACHOU-SAC done
-> row 323 || KXNBAGAME-25DEC04UTABKN-UTA done
-> row 324 || KXNBAGAME-25DEC04GSWPHI-GSW done
-> row 325 || KXNBAGAME-25DEC04MINNOP-MIN done
-> row 326 || KXNBAGAME-25DEC04LALTOR-LAL done
-> row 327 || KXNBAGAME-25DEC04BOSWAS-BOS done
-> row 328 || KXNBAGAME-25DEC05PHIMIL-PHI done
-> row 329 || KXNBAGAME-25DEC05UTANYK-UTA done
-> row 330 || KXNBAGAME-25DEC05MIAORL-MIA done
-> row 331 || KXNBAGAME-25DEC05DALOKC-DAL done
-> row 332 || KXNBAGAME-25DEC05DENATL-DEN done
-> row 333 || KXNBAGAME-25DEC05LALBOS-LAL done
-> row 334 || KXNBAGAME-25DEC05SASCLE-SAS done
-> row 335 || KXNBAGAME-25DEC05INDCHI-IND done
-> row 336 || KXNBAGAME-25DEC05PHXHOU-PHX done
-> row 337 || KXNBAGAME-25DEC05CHATOR-CHA done
-> row 338 || KXNBAGAME-25DEC05LACMEM-LAC done
-> row 339 || KXNBAGAME-25DEC05PORDET-POR done
-> row 340 || KXNBAGAME-25DEC06LACMIN-LAC done
-> row 341 || KXNBAGAME-25DEC06NOPBKN-NOP done
-> row 342 || KXNBAGAME-25DEC06GSWCLE-GSW done
-> row 343 || KXNBAGAME-25DEC06HOUDAL-HOU done
-> row 344 || KXNBAGAME-25DEC06SACMIA-SAC done
-> row 345 || KXNBAGAME-25DEC06ATLWAS-ATL done
-> row 346 || KXNBAGAME-25DEC06MILDET-MIL done
-> row 347 || KXNBAGAME-25DEC07ORLNYK-ORL done
-> row 348 || KXNBAGAME-25DEC07LALPHI-LAL done
-> row 349 || KXNBAGAME-25DEC07GSWCHI-GSW done
-> row 350 || KXNBAGAME-25DEC07BOSTOR-BOS done
-> row 351 || KXNBAGAME-25DEC07OKCUTA-OKC done
-> row 352 || KXNBAGAME-25DEC07PORMEM-POR done
-> row 353 || KXNBAGAME-25DEC07DENCHA-DEN done
-> row 354 || KXNBAGAME-25DEC08PHXMIN-PHX done
-> row 355 || KXNBAGAME-25DEC08SACIND-SAC done
-> row 356 || KXNBAGAME-25DEC08SASNOP-SAS done
-> row 357 || KXNBAGAME-25DEC09MIAORL-MIA done
-> row 358 || KXNBAGAME-25DEC09NYKTOR-NYK done
-> row 359 || KXNBAGAME-25DEC10PHXOKC-PHX done
-> row 360 || KXNBAGAME-25DEC10SASLAL-SAS done
-> row 361 || KXNBAGAME-25DEC11BOSMIL-BOS done
-> row 362 || KXNBAGAME-25DEC11DENSAC-DEN done
-> row 363 || KXNBAGAME-25DEC11PORNOP-POR done
-> row 364 || KXNBAGAME-25DEC11LACHOU-LAC done
-> row 365 || KXNBAGAME-25DEC12INDPHI-IND done
-> row 366 || KXNBAGAME-25DEC12BKNDAL-BKN done
-> row 367 || KXNBAGAME-25DEC12MINGSW-MIN done
-> row 368 || KXNBAGAME-25DEC12UTAMEM-UTA done
-> row 369 || KXNBAGAME-25DEC12CLEWAS-CLE done
-> row 370 || KXNBAGAME-25DEC12ATLDET-ATL done
-> row 371 || KXNBAGAME-25DEC12CHICHA-CHI done
-> row 372 || KXNBAGAME-25DEC14SACMIN-SAC done
-> row 373 || KXNBAGAME-25DEC14MILBKN-MIL done
-> row 374 || KXNBAGAME-25DEC14WASIND-WAS done
-> row 375 || KXNBAGAME-25DEC14LALPHX-LAL done
-> row 376 || KXNBAGAME-25DEC14GSWPOR-GSW done
-> row 377 || KXNBAGAME-25DEC14PHIATL-PHI done
-> row 378 || KXNBAGAME-25DEC14CHACLE-CHA done
-> row 379 || KXNBAGAME-25DEC14NOPCHI-NOP done
-> row 380 || KXNBAGAME-25DEC15DETBOS-DET done
-> row 381 || KXNBAGAME-25DEC15HOUDEN-HOU done
-> row 382 || KXNBAGAME-25DEC15MEMLAC-MEM done
-> row 383 || KXNBAGAME-25DEC15TORMIA-TOR done
-> row 384 || KXNBAGAME-25DEC15DALUTA-DAL done
-> row 385 || KXNBAGAME-25DEC17MEMMIN-MEM done
-> row 386 || KXNBAGAME-25DEC17CLECHI-CLE done
-> row 387 || KXNBAGAME-25DEC18TORMIL-TOR done
-> row 388 || KXNBAGAME-25DEC18MIABKN-MIA done
-> row 389 || KXNBAGAME-25DEC18NYKIND-NYK done
-> row 390 || KXNBAGAME-25DEC18GSWPHX-GSW done
-> row 391 || KXNBAGAME-25DEC18SACPOR-SAC done
-> row 392 || KXNBAGAME-25DEC18WASSAS-WAS done
-> row 393 || KXNBAGAME-25DEC18LACOKC-LAC done
-> row 394 || KXNBAGAME-25DEC18HOUNOP-HOU done
-> row 395 || KXNBAGAME-25DEC18DETDAL-DET done
-> row 396 || KXNBAGAME-25DEC18ORLDEN-ORL done
-> row 397 || KXNBAGAME-25DEC18LALUTA-LAL done
-> row 398 || KXNBAGAME-25DEC18ATLCHA-ATL done
-> row 399 || KXNBAGAME-25DEC19OKCMIN-OKC done
-> row 400 || KXNBAGAME-25DEC19PHINYK-PHI done
-> row 401 || KXNBAGAME-25DEC19SASATL-SAS done
-> row 402 || KXNBAGAME-25DEC19MIABOS-MIA done
-> row 403 || KXNBAGAME-25DEC19CHICLE-CHI done
-> row 404 || KXNBAGAME-25DEC20DALPHI-DAL done
-> row 405 || KXNBAGAME-25DEC20PORSAC-POR done
-> row 406 || KXNBAGAME-25DEC20INDNOP-IND done
-> row 407 || KXNBAGAME-25DEC20HOUDEN-HOU done
-> row 408 || KXNBAGAME-25DEC20PHXGSW-PHX done
-> row 409 || KXNBAGAME-25DEC20LALLAC-LAL done
-> row 410 || KXNBAGAME-25DEC20BOSTOR-BOS done
-> row 411 || KXNBAGAME-25DEC20ORLUTA-ORL done
-> row 412 || KXNBAGAME-25DEC20WASMEM-WAS done
-> row 413 || KXNBAGAME-25DEC20CHADET-CHA done
-> row 414 || KXNBAGAME-25DEC21MILMIN-MIL done
-> row 415 || KXNBAGAME-25DEC21TORBKN-TOR done
-> row 416 || KXNBAGAME-25DEC21MIANYK-MIA done
-> row 417 || KXNBAGAME-25DEC21HOUSAC-HOU done
-> row 418 || KXNBAGAME-25DEC21CHIATL-CHI done
-> row 419 || KXNBAGAME-25DEC21SASWAS-SAS done
-> row 420 || KXNBAGAME-25DEC22DETPOR-DET done
-> row 421 || KXNBAGAME-25DEC22MEMOKC-MEM done
-> row 422 || KXNBAGAME-25DEC22INDBOS-IND done
-> row 423 || KXNBAGAME-25DEC22CHACLE-CHA done
-> row 424 || KXNBAGAME-25DEC22DALNOP-DAL done
-> row 425 || KXNBAGAME-25DEC22UTADEN-UTA done
-> row 426 || KXNBAGAME-25DEC22ORLGSW-ORL done
-> row 427 || KXNBAGAME-25DEC23NYKMIN-NYK done

,KALSHI_ID,TIMESTAMP,end_period_ts,open_interest,volume,price_close,price_high,price_low,price_mean,price_open
0,KXNBAGAME-25OCT21HOUOKC-HOU,2025-10-21 19:00:00+00:00,1761073200,625472.0,96317.0,0.31,0.31,0.30,0.3098,0.31
1,KXNBAGAME-25OCT21GSWLAL-GSW,2025-10-21 22:00:00+00:00,1761084000,605829.0,106223.0,0.59,0.59,0.58,0.5891,0.59
2,KXNBAGAME-25OCT22WASMIL-WAS,2025-10-22 20:00:00+00:00,1761163200,112969.0,6784.0,0.20,0.20,0.19,0.1998,0.20
3,KXNBAGAME-25OCT22CLENYK-CLE,2025-10-22 19:00:00+00:00,1761159600,626019.0,181277.0,0.54,0.60,0.53,0.5537,0.59
4,KXNBAGAME-25OCT22MIAORL-MIA,2025-10-22 19:00:00+00:00,1761159600,276332.0,102947.0,0.24,0.25,0.23,0.2454,0.25
...,...,...,...,...,...,...,...,...,...,...
2443,KXNBAGAME-26APR12MEMHOU-HOU,2026-04-12 20:00:00+00:00,1776024000,46522.0,11249.0,0.90,0.90,0.88,0.8949,0.89
2444,KXNBAGAME-26APR12GSWLAC-LAC,2026-04-12 20:00:00+00:00,1776024000,68095.0,5267.0,0.70,0.70,0.70,0.7000,0.70
2445,KXNBAGAME-26APR12UTALAL-LAL,2026-04-12 20:00:00+00:00,1776024000,150827.0,8361.0,0.88,0.89,0.88,0.8898,0.89
2446,KXNBAGAME-26APR12ATLMIA-MIA,2026-04-12 18:00:00+00:00,1776016800,342637.0,130803.0,0.76,0.77,0.65,0.7300,0.65
2447,KXNBAGAME-26APR12BKNTOR-TOR,2026-04-12 18:00:00+00:00,1776016800,206294.0,9292.0,0.98,0.98,0.96,0.9712,0.97

In [ ]:
test4.to_csv("../data/kalshi(pre-game).csv", index=False)

### Kalshi In-Game Fetch

fill this out later