# Notebook title

description here

### Import Libraries

fill this out later

In [1]:
import time
import requests
import pandas as pd
import numpy as np
from nba_api.stats.endpoints import playbyplayv3

pd.set_option('display.max_columns', None)

SEASON = "2025-26"
REQUEST_DELAY_SECONDS = 0.25
BASE_URL = "https://external-api.kalshi.com/trade-api/v2"
DATA = "../data/_team-box-stats(full-game).csv"

### Establish Key Functions

fill this out later

In [ ]:
# ------------------------------------------------------------------------- #
######### CONSOLIDATE REGULAR SEASON GAMES #########
def game_consolidation(season_data):
    '''
    Fill this out later
    '''
    df = pd.read_csv(season_data, dtype={"GAME_ID": str})
    df = df.drop(columns=[
        "TEAM_ID", "FGM", "FGA", "FG_PCT", "FG3M", "FG3A", "FG3_PCT",
        "FTM", "FTA", "FT_PCT", "OREB", "DREB", "REB", "AST", "STL", "BLK", "TOV", "PF", "PLUS_MINUS"
    ])
    home = df[df["MATCHUP"].str.contains("vs.")]
    away = df[df["MATCHUP"].str.contains("@")]
    games = home.merge(away, on="GAME_ID", suffixes=("_HOME", "_AWAY"))
    games = games.rename(columns={"MATCHUP_AWAY": 'MATCHUP'})
    games['WINNER'] = np.where(games['WL_HOME'] == "W", games['TEAM_NAME_HOME'], games['TEAM_NAME_AWAY'])
    games = games[[
        "GAME_ID", "GAME_DATE_HOME", "MATCHUP", 
        "TEAM_ABBREVIATION_AWAY", "TEAM_NAME_AWAY", "PTS_AWAY",
        "TEAM_ABBREVIATION_HOME", "TEAM_NAME_HOME", "PTS_HOME", "WINNER"
    ]]
    return games



# ------------------------------------------------------------------------- #
######### GET THE EXACT START TIME FOR EVERY GAME BY QUARTER #########
def pull_quarter_start_times(game_ids, period):
    '''
    fill this out later
    '''
    rows = []
    for gid in game_ids:
        pbp = playbyplayv3.PlayByPlayV3(game_id=gid).get_data_frames()[0]
        starts = pbp[(pbp["period"] == period) & (pbp["subType"].str.lower() == "start")]
        rows.append(starts[["gameId", "period", "description"]])
        time.sleep(REQUEST_DELAY_SECONDS)
        #print(f"{gid} done")
    # create df
    df = pd.concat(rows, ignore_index=True)
    # extract the start time from each row "Start of 1st Period (10:18 PM EST)""
    df["description"] = df["description"].str.split("(").str[-1].str.rstrip(")")
    # rename columns for clarity
    df = df.rename(columns={
        "gameId": "GAME_ID",
        "period": "PERIOD",
        "description": "EXACT_START_TIME"
    })
    return df



# ------------------------------------------------------------------------- #
######### CREATE DF WITH KALSHI MARKET TICKERS AND TIMESTAMPS #########
def games_with_kalshi_info_converter(df1, df2):
    '''
    Fill this out later
    '''
    # merge the two dfs on GAME_ID using inner
    merged = pd.merge(df1, df2, on="GAME_ID", how="inner")
    # rename columns for clarity
    merged = merged.rename(columns={
        "PERIOD": "QUARTER",
        "GAME_DATE_HOME": "GAME_DATE",
        "TEAM_ABBREVIATION_AWAY": "ABBR_AWAY",
        "TEAM_NAME_AWAY": "NAME_AWAY",
        "TEAM_ABBREVIATION_HOME": "ABBR_HOME",
        "TEAM_NAME_HOME": "NAME_HOME",
    })
    # convert object columns to strings
    merged["ABBR_AWAY"] = merged["ABBR_AWAY"].astype(str)
    merged["ABBR_HOME"] = merged["ABBR_HOME"].astype(str)
    # the
    merged["gameDateTimeEst"] = pd.to_datetime(
        merged["GAME_DATE"].astype(str) + " " + 
        merged["EXACT_START_TIME"].str.rsplit(" ", n=1).str[0],
        format="mixed"
    )
    # convert gameDateTimeEst column from object to datetieme
    merged["gameDateTimeEst"] = pd.to_datetime(merged["gameDateTimeEst"])
    # create new column for clarity using 12 hour clock
    merged["QUARTER_START(EST)"] = (merged["gameDateTimeEst"].dt.strftime("%I:%M%p").str.lstrip("0"))
    # create Kalshi market ID's for away teams
    merged['KALSHI_ID_AWAY'] = ('KXNBAGAME-' +
        merged['gameDateTimeEst'].dt.strftime('%y') +
        merged['gameDateTimeEst'].dt.strftime('%b').str.upper() +
        merged['gameDateTimeEst'].dt.strftime('%d') + 
        merged['ABBR_AWAY'] +
        merged['ABBR_HOME'] + '-' +
        merged['ABBR_AWAY']
    )
    # create Kalshi market ID's for home teams
    merged['KALSHI_ID_HOME'] = ('KXNBAGAME-' + 
        merged['gameDateTimeEst'].dt.strftime('%y') +
        merged['gameDateTimeEst'].dt.strftime('%b').str.upper() +
        merged['gameDateTimeEst'].dt.strftime('%d') + 
        merged['ABBR_AWAY'] +
        merged['ABBR_HOME'] + '-' +
        merged['ABBR_HOME']
    )
    # create a timestamp column that will be used for fetching Kalshi data later
    merged['TIMESTAMP'] = (merged['gameDateTimeEst'].astype('int64') // 1_000_000_000)
    # reorganize final column order
    merged = merged[[
        "GAME_ID", "QUARTER", "QUARTER_START(EST)", "GAME_DATE", "TIMESTAMP", 
        "KALSHI_ID_AWAY", "KALSHI_ID_HOME", "MATCHUP", 
        "ABBR_AWAY", "NAME_AWAY", "PTS_AWAY", 
        "ABBR_HOME", "NAME_HOME", "PTS_HOME",
        "WINNER"
    ]]
    return merged



# ------------------------------------------------------------------------- #
######### CREATE DF WITH KALSHI MARKET TICKERS AND TIMESTAMPS #########
def fetch_kalshi_candlesticks(ticker, end_ts, period_interval=1):
    """
    Use this funciton to fetch historical candlestick data from the Kalshi API.
    PARAMETERS;
        - ticker (str): market ticker symbol ('KXNBAGAME-25OCT21GSWLAL-GSW')
        - end_ts (int): timestamp marking the ending of the desired period (start of the game)
        - period_interval (int): time period length of each candlestick in minutes (60=1hr candles, 1=1min candles)
    Returns (DF);
        - KALSHI_ID (str): the unique market identifier
        - TIMESTAMP (datetime): date and time of candlestick ending
        - end_period_ts (int): timestamp of the candle close
        - open_interest (str): number of contracts still open by end of the candlestick period
        - volume (str): number of contracts bought on the market during the candlestick period
        - price_close (float): price of the last trade during the candlestick period
        - price_high (float): highest trade price during the candlestick period
        - price_low (float): lowest trade price during the candlestick period
        - price_mean (float): volume weighted average price during the candlestick period
        - price_open (float): price of the first trade during the candlestick period
    """
    # get all the candle stick data for exactly 5 minutes before tipoff
    # the '+ 1' here nudges the start by one sec so we don’t also pick up the previous minute’s candle
    start_ts = end_ts - 5 * 60 + 1
    # list that will collect candlestick dicts from every chunk
    all_candles = []
    # send http get requests to the historical candlesticks endpoint
    response = requests.get(
        f"{BASE_URL}/historical/markets/{ticker}/candlesticks",
        params={'start_ts': start_ts, 'end_ts': end_ts, 'period_interval': period_interval},
        timeout=10)
    # error handling for if the market doesn't exist (or ticker info is wrong), or any other error
    if response.status_code == 404:
        print(f"Market {ticker} not found (404) - skipping")
        return pd.DataFrame()
    response.raise_for_status()
    # parse the JSON response and append this chunk’s candles to our list
    all_candles.extend(response.json()['candlesticks'])
    # necessary pause between requests to avoid Kalshi API rate limits
    time.sleep(REQUEST_DELAY_SECONDS)
    # flatten the nested candle dicts into a table; nested keys joined sep
    df = pd.json_normalize(all_candles, sep='_')
    # fill this out later
    if df.empty or 'end_period_ts' not in df.columns:
        return pd.DataFrame()
    # add ticker and datetime columns 
    df.insert(0, 'KALSHI_ID', ticker)
    df.insert(1, 'TIMESTAMP', pd.to_datetime(df['end_period_ts'], unit='s', utc=True))
    # keep only the last candle (one row per ticker), ensures there is at least 1 row
    df = df.sort_values("end_period_ts").tail(1).reset_index(drop=True)
    # drop unnecessary columns
    df = df.drop(columns=[
        "price_previous", 
        #"yes_ask_close", "yes_ask_high", "yes_ask_low", "yes_ask_open", 
        #"yes_bid_close", "yes_bid_high", "yes_bid_low", "yes_bid_open"
    ])
    # convert columns to float
    float_cols = [
        "open_interest", "volume", "price_close", "price_high",
        "price_low", "price_mean", "price_open",
    ]
    df[float_cols] = df[float_cols].apply(pd.to_numeric, errors="coerce").round(4)
    return df



# ------------------------------------------------------------------------- #
######### CREATE DF WITH KALSHI MARKET TICKERS AND TIMESTAMPS #########
def kalshi_price_df_generator(game_dict):
    '''
    fill this out later
    '''
    count = 0
    all_dfs = []
    for ticker, ts in game_dict.items():
        df = fetch_kalshi_candlesticks(ticker, ts)
        if df.empty:
            print(f"-> skipped {ticker}")
            continue
        count += 1
        #print(f"-> row {count} || {ticker} done")
        all_dfs.append(df)

    combined = pd.concat(all_dfs, ignore_index=True)
    return combined

### Consolidate games 

fill this out later

In [5]:
games_df = game_consolidation(DATA)
games_df.head(3)

,GAME_ID,GAME_DATE_HOME,MATCHUP,TEAM_ABBREVIATION_AWAY,TEAM_NAME_AWAY,PTS_AWAY,TEAM_ABBREVIATION_HOME,TEAM_NAME_HOME,PTS_HOME,WINNER
0,0022500002,2025-10-21,GSW @ LAL,GSW,Golden State Warriors,119,LAL,Los Angeles Lakers,109,Golden State Warriors
1,0022500001,2025-10-21,HOU @ OKC,HOU,Houston Rockets,124,OKC,Oklahoma City Thunder,125,Oklahoma City Thunder
2,0022500086,2025-10-22,WAS @ MIL,WAS,Washington Wizards,120,MIL,Milwaukee Bucks,133,Milwaukee Bucks

### Get The Unique Game ID's then Pull Start Times By Quarter

fill this out later

In [6]:
game_ids = games_df["GAME_ID"].tolist()

In [ ]:
# Takes about 10mins
q1_start_times = pull_quarter_start_times(game_ids=game_ids, period=1)
q1_start_times.head(3)

      GAME_ID  PERIOD EXACT_START_TIME
0  0022500002       1     10:18 PM EST
1  0022500001       1      7:44 PM EST
2  0022500086       1      8:14 PM EST

In [ ]:
# Takes about 10mins
q2_start_times = pull_quarter_start_times(game_ids=game_ids, period=2)
q2_start_times.head(3)

In [ ]:
# Takes about 10mins
q3_start_times = pull_quarter_start_times(game_ids=game_ids, period=3)
q3_start_times.head(3)

In [ ]:
# Takes about 10mins
q4_start_times = pull_quarter_start_times(game_ids=game_ids, period=4)
q4_start_times.head(3)

### Create DF With Kalshi Tickers and Quarter Start Times

fill this out later

In [19]:
q1_start_with_kalshi = games_with_kalshi_info_converter(games_df, q1_start_times)
q1_start_with_kalshi.head(3)

,GAME_ID,QUARTER,QUARTER_START(EST),GAME_DATE,TIMESTAMP,KALSHI_ID_AWAY,KALSHI_ID_HOME,MATCHUP,ABBR_AWAY,NAME_AWAY,PTS_AWAY,ABBR_HOME,NAME_HOME,PTS_HOME,WINNER
0,0022500002,1,10:18PM,2025-10-21,1761085080,KXNBAGAME-25OCT21GSWLAL-GSW,KXNBAGAME-25OCT21GSWLAL-LAL,GSW @ LAL,GSW,Golden State Warriors,119,LAL,Los Angeles Lakers,109,Golden State Warriors
1,0022500001,1,7:44PM,2025-10-21,1761075840,KXNBAGAME-25OCT21HOUOKC-HOU,KXNBAGAME-25OCT21HOUOKC-OKC,HOU @ OKC,HOU,Houston Rockets,124,OKC,Oklahoma City Thunder,125,Oklahoma City Thunder
2,0022500086,1,8:14PM,2025-10-22,1761164040,KXNBAGAME-25OCT22WASMIL-WAS,KXNBAGAME-25OCT22WASMIL-MIL,WAS @ MIL,WAS,Washington Wizards,120,MIL,Milwaukee Bucks,133,Milwaukee Bucks

In [ ]:
q2_start_with_kalshi = games_with_kalshi_info_converter(games_df, q2_start_times)
q2_start_with_kalshi.head(3)

In [ ]:
q3_start_with_kalshi = games_with_kalshi_info_converter(games_df, q3_start_times)
q3_start_with_kalshi.head(3)

In [ ]:
q4_start_with_kalshi = games_with_kalshi_info_converter(games_df, q4_start_times)
q4_start_with_kalshi.head(3)

In [10]:
q1_start_times.to_csv("../data/_main(all-games).csv", index=False)

### Pull Kalshi Data By Quarter

fill this out later

In [20]:
q1_game_dict = dict(zip(q1_start_with_kalshi['KALSHI_ID_AWAY'], q1_start_with_kalshi['TIMESTAMP'])) | dict(zip(q1_start_with_kalshi['KALSHI_ID_HOME'], q1_start_with_kalshi['TIMESTAMP']))
#q2_game_dict = dict(zip(q1_start_with_kalshi['KALSHI_ID_AWAY'], q1_start_with_kalshi['TIMESTAMP'])) | dict(zip(q1_start_with_kalshi['KALSHI_ID_HOME'], q1_start_with_kalshi['TIMESTAMP']))
#q1_game_dict = dict(zip(q1_start_with_kalshi['KALSHI_ID_AWAY'], q1_start_with_kalshi['TIMESTAMP'])) | dict(zip(q1_start_with_kalshi['KALSHI_ID_HOME'], q1_start_with_kalshi['TIMESTAMP']))
#q1_game_dict = dict(zip(q1_start_with_kalshi['KALSHI_ID_AWAY'], q1_start_with_kalshi['TIMESTAMP'])) | dict(zip(q1_start_with_kalshi['KALSHI_ID_HOME'], q1_start_with_kalshi['TIMESTAMP']))

In [ ]:
# Takes about 20mins
kalshi_q1_prices = kalshi_price_df_generator(q1_game_dict)
kalshi_q1_prices.head(3)

Market KXNBAGAME-26JAN25GSWMIN-GSW not found (404) - skipping
-> skipped KXNBAGAME-26JAN25GSWMIN-GSW
Market KXNBAGAME-26JAN25GSWMIN-MIN not found (404) - skipping
-> skipped KXNBAGAME-26JAN25GSWMIN-MIN
-> skipped KXNBAGAME-26APR10NOPBOS-BOS
-> skipped KXNBAGAME-26APR12BKNTOR-TOR

,KALSHI_ID,TIMESTAMP,end_period_ts,open_interest,volume,price_close,price_high,price_low,price_mean,price_open,yes_ask_close,yes_ask_high,yes_ask_low,yes_ask_open,yes_bid_close,yes_bid_high,yes_bid_low,yes_bid_open
0,KXNBAGAME-25OCT21GSWLAL-GSW,2025-10-21 22:18:00+00:00,1761085080,643140.0,2122.0,0.59,0.59,0.59,0.5900,0.59,0.5900,0.5900,0.5900,0.5900,0.5800,0.5800,0.5800,0.5800
1,KXNBAGAME-25OCT21HOUOKC-HOU,2025-10-21 19:44:00+00:00,1761075840,760802.0,954.0,0.31,0.31,0.30,0.3099,0.31,0.3100,0.3100,0.3100,0.3100,0.3000,0.3000,0.3000,0.3000
2,KXNBAGAME-25OCT22WASMIL-WAS,2025-10-22 20:14:00+00:00,1761164040,112869.0,2.0,0.20,0.20,0.20,0.2000,0.20,0.2000,0.2000,0.2000,0.2000,0.1900,0.1900,0.1900,0.1900

In [ ]:
# Takes about 20mins
kalshi_q2_prices = kalshi_price_df_generator(q1_game_dict)
kalshi_q2_prices.head(4)

In [ ]:
# Takes about 20mins
kalshi_q1_prices = kalshi_price_df_generator(q1_game_dict)
kalshi_q1_prices.head(4)

In [ ]:
# Takes about 20mins
kalshi_q1_prices = kalshi_price_df_generator(q1_game_dict)
kalshi_q1_prices.head(4)

In [ ]:
kalshi_q1_prices.to_csv("../data/kalshi(_pre-game).csv", index=False)
#kalshi_q1_prices.to_csv("../data/kalshi(_pre-game).csv", index=False)
#kalshi_q1_prices.to_csv("../data/kalshi(_pre-game).csv", index=False)
#kalshi_q1_prices.to_csv("../data/kalshi(_pre-game).csv", index=False)