# Notebook title

description here

### Import Libraries

In [1]:
import pandas as pd
from nba_api.stats.endpoints import leaguegamelog

pd.set_option('display.max_columns', None)

SEASON = "2025-26"

### Raw box score data

fill out later

In [2]:
def raw_team_box_score_stats(years):
    '''
    Fill this out later
    '''
    teams = leaguegamelog.LeagueGameLog(
        season=years,
        season_type_all_star="Regular Season",
        player_or_team_abbreviation="T",
    ).get_data_frames()[0]

    teams = teams.drop(columns=["MIN", "VIDEO_AVAILABLE"])
    
    return teams


test = raw_team_box_score_stats(SEASON)
test

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS
0,22025,1610612760,OKC,Oklahoma City Thunder,0022500001,2025-10-21,OKC vs. HOU,W,46,104,0.442,13,52,0.250,20,25,0.800,11,27,38,29,12,4,12,27,125,1
1,22025,1610612744,GSW,Golden State Warriors,0022500002,2025-10-21,GSW @ LAL,W,38,78,0.487,17,40,0.425,26,29,0.897,9,31,40,29,10,4,19,27,119,10
2,22025,1610612745,HOU,Houston Rockets,0022500001,2025-10-21,HOU @ OKC,L,43,97,0.443,11,39,0.282,27,31,0.871,16,36,52,23,6,5,25,26,124,-1
3,22025,1610612747,LAL,Los Angeles Lakers,0022500002,2025-10-21,LAL vs. GSW,L,42,77,0.545,8,32,0.250,17,28,0.607,7,32,39,23,7,2,20,21,109,-10
4,22025,1610612749,MIL,Milwaukee Bucks,0022500086,2025-10-22,MIL vs. WAS,W,50,98,0.510,18,44,0.409,15,19,0.789,6,40,46,31,8,6,8,22,133,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,22025,1610612762,UTA,Utah Jazz,0022501198,2026-04-12,UTA @ LAL,L,41,94,0.436,7,34,0.206,18,27,0.667,17,25,42,25,13,4,16,14,107,-24
2456,22025,1610612763,MEM,Memphis Grizzlies,0022501194,2026-04-12,MEM @ HOU,L,39,95,0.411,13,49,0.265,10,10,1.000,6,31,37,23,8,6,13,24,101,-31
2457,22025,1610612764,WAS,Washington Wizards,0022501187,2026-04-12,WAS @ CLE,L,42,90,0.467,18,41,0.439,15,19,0.789,7,23,30,29,10,2,13,21,117,-13
2458,22025,1610612765,DET,Detroit Pistons,0022501188,2026-04-12,DET @ IND,W,50,89,0.562,15,33,0.455,18,22,0.818,12,36,48,35,12,6,18,17,133,12
2459,22025,1610612766,CHA,Charlotte Hornets,0022501190,2026-04-12,CHA @ NYK,W,39,85,0.459,19,52,0.365,13,17,0.765,12,34,46,27,7,7,18,13,110,14

In [ ]:
test.to_csv("../data/raw-team-box-score(full-game).csv", index=False)

### Rolling data

fill this out later

In [4]:
def rolling_avg_team_box_score_stats(years, prev_games=3):
    '''
    Fill this out later
    '''
    teams = leaguegamelog.LeagueGameLog(
        season=years,
        season_type_all_star="Regular Season",
        player_or_team_abbreviation="T",
    ).get_data_frames()[0]

    stats = [
        "FGM", "FGA", "FG_PCT", "FG3M", "FG3A", "FG3_PCT", "FTM", "FTA", "FT_PCT", 
        "OREB", "DREB", "REB", "AST", "STL", "BLK", "TOV", "PF", "PTS", "PLUS_MINUS"
    ]

    teams[stats] = (teams.groupby("TEAM_ID")[stats].transform(lambda s: s.rolling(prev_games).mean().round(2)))
    teams = teams.rename(columns={s: f"{prev_games}_game_roll_avg_{s}" for s in stats})
    teams = teams.drop(columns=["MIN", "VIDEO_AVAILABLE"])

    return teams.dropna(subset=[f"{prev_games}_game_roll_avg_{s}" for s in stats])


test1 = rolling_avg_team_box_score_stats(SEASON, prev_games=3)
test1

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,3_game_roll_avg_FGM,3_game_roll_avg_FGA,3_game_roll_avg_FG_PCT,3_game_roll_avg_FG3M,3_game_roll_avg_FG3A,3_game_roll_avg_FG3_PCT,3_game_roll_avg_FTM,3_game_roll_avg_FTA,3_game_roll_avg_FT_PCT,3_game_roll_avg_OREB,3_game_roll_avg_DREB,3_game_roll_avg_REB,3_game_roll_avg_AST,3_game_roll_avg_STL,3_game_roll_avg_BLK,3_game_roll_avg_TOV,3_game_roll_avg_PF,3_game_roll_avg_PTS,3_game_roll_avg_PLUS_MINUS
46,22025,1610612744,GSW,Golden State Warriors,0022500097,2025-10-24,GSW @ POR,L,41.00,85.67,0.48,17.00,41.67,0.41,26.00,31.00,0.83,10.33,31.00,41.33,28.67,11.00,3.33,17.67,21.67,125.00,-1.33
56,22025,1610612753,ORL,Orlando Magic,0022500100,2025-10-25,ORL vs. CHI,L,37.67,85.00,0.44,8.00,28.33,0.27,26.67,35.00,0.77,12.00,36.00,48.00,18.67,7.67,5.00,19.00,23.67,110.00,-4.00
59,22025,1610612756,PHX,Phoenix Suns,0022500104,2025-10-25,PHX @ DEN,L,40.00,91.00,0.44,14.33,43.67,0.32,16.67,21.67,0.78,15.00,27.00,42.00,23.33,8.67,5.00,18.00,26.33,111.00,-15.00
60,22025,1610612760,OKC,Oklahoma City Thunder,0022500101,2025-10-25,OKC @ ATL,W,44.00,97.33,0.45,12.33,41.33,0.30,27.33,31.67,0.86,11.67,37.67,49.33,22.33,10.33,3.00,13.00,26.33,127.67,8.00
61,22025,1610612737,ATL,Atlanta Hawks,0022500101,2025-10-25,ATL vs. OKC,L,38.00,86.67,0.44,11.33,34.33,0.32,22.33,28.67,0.76,10.67,29.33,40.00,25.33,7.67,5.33,16.33,22.67,109.67,-11.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,22025,1610612762,UTA,Utah Jazz,0022501198,2026-04-12,UTA @ LAL,L,52.00,102.67,0.50,10.67,33.67,0.32,15.67,22.67,0.67,13.00,36.00,49.00,35.33,13.67,3.33,16.00,13.67,130.33,1.00
2456,22025,1610612763,MEM,Memphis Grizzlies,0022501194,2026-04-12,MEM @ HOU,L,40.67,98.67,0.41,14.33,50.33,0.29,11.33,14.00,0.86,9.00,31.67,40.67,24.67,7.67,3.00,13.00,19.67,107.00,-31.33
2457,22025,1610612764,WAS,Washington Wizards,0022501187,2026-04-12,WAS @ CLE,L,42.00,92.67,0.45,14.00,36.67,0.38,16.00,20.00,0.80,11.00,25.33,36.33,26.33,11.00,4.00,15.33,18.67,114.00,-15.67
2458,22025,1610612765,DET,Detroit Pistons,0022501188,2026-04-12,DET @ IND,W,47.67,87.33,0.55,12.67,30.00,0.42,21.33,26.00,0.82,14.33,33.33,47.67,34.00,11.33,8.00,15.00,19.33,129.33,18.67
2459,22025,1610612766,CHA,Charlotte Hornets,0022501190,2026-04-12,CHA @ NYK,W,37.00,87.00,0.43,16.00,49.33,0.32,14.00,17.67,0.79,13.33,29.00,42.33,22.33,7.33,6.00,15.67,15.33,104.00,-5.00

In [ ]:
test1.to_csv("../data/roll-avg-only(3GAME).csv", index=False)

In [ ]:
test2 = rolling_avg_team_box_score_stats(SEASON, prev_games=5)
test2.to_csv("../data/roll-avg-only(5GAME).csv", index=False)

test3 = rolling_avg_team_box_score_stats(SEASON, prev_games=10)
test3.to_csv("../data/roll-avg-only(10GAME).csv", index=False)

test4 = rolling_avg_team_box_score_stats(SEASON, prev_games=15)
test4.to_csv("../data/roll-avg-only(15GAME).csv", index=False)

### In-Game Data

Fill this out later