# Notebook title

description here

### Import Libraries

In [1]:
import pandas as pd
from nba_api.stats.endpoints import leaguegamelog

pd.set_option('display.max_columns', None)

SEASON = "2025-26"

### Raw box score data

fill out later

In [2]:
def raw_team_box_score_stats(years):
    '''
    Fill this out later
    '''
    teams = leaguegamelog.LeagueGameLog(
        season=years,
        season_type_all_star="Regular Season",
        player_or_team_abbreviation="T",
    ).get_data_frames()[0]

    teams = teams.drop(columns=["MIN", "VIDEO_AVAILABLE"])
    
    return teams

In [3]:
test = raw_team_box_score_stats(SEASON)
test

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS
0,22025,1610612747,LAL,Los Angeles Lakers,0022500002,2025-10-21,LAL vs. GSW,L,42,77,0.545,8,32,0.250,17,28,0.607,7,32,39,23,7,2,20,21,109,-10
1,22025,1610612744,GSW,Golden State Warriors,0022500002,2025-10-21,GSW @ LAL,W,38,78,0.487,17,40,0.425,26,29,0.897,9,31,40,29,10,4,19,27,119,10
2,22025,1610612745,HOU,Houston Rockets,0022500001,2025-10-21,HOU @ OKC,L,43,97,0.443,11,39,0.282,27,31,0.871,16,36,52,23,6,5,25,26,124,-1
3,22025,1610612760,OKC,Oklahoma City Thunder,0022500001,2025-10-21,OKC vs. HOU,W,46,104,0.442,13,52,0.250,20,25,0.800,11,27,38,29,12,4,12,27,125,1
4,22025,1610612746,LAC,LA Clippers,0022500087,2025-10-22,LAC @ UTA,L,39,88,0.443,14,45,0.311,16,21,0.762,15,23,38,28,8,6,15,21,108,-21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,22025,1610612762,UTA,Utah Jazz,0022501198,2026-04-12,UTA @ LAL,L,41,94,0.436,7,34,0.206,18,27,0.667,17,25,42,25,13,4,16,14,107,-24
2456,22025,1610612763,MEM,Memphis Grizzlies,0022501194,2026-04-12,MEM @ HOU,L,39,95,0.411,13,49,0.265,10,10,1.000,6,31,37,23,8,6,13,24,101,-31
2457,22025,1610612764,WAS,Washington Wizards,0022501187,2026-04-12,WAS @ CLE,L,42,90,0.467,18,41,0.439,15,19,0.789,7,23,30,29,10,2,13,21,117,-13
2458,22025,1610612765,DET,Detroit Pistons,0022501188,2026-04-12,DET @ IND,W,50,89,0.562,15,33,0.455,18,22,0.818,12,36,48,35,12,6,18,17,133,12
2459,22025,1610612766,CHA,Charlotte Hornets,0022501190,2026-04-12,CHA @ NYK,W,39,85,0.459,19,52,0.365,13,17,0.765,12,34,46,27,7,7,18,13,110,14

In [10]:
test.to_csv("../data/2025_raw_box_score_team_stats.csv", index=False)

### Rolling data

fill this out later

In [8]:
def rolling_avg_team_box_score_stats(years, prev_games=3):
    '''
    Fill this out later
    '''
    teams = leaguegamelog.LeagueGameLog(
        season=years,
        season_type_all_star="Regular Season",
        player_or_team_abbreviation="T",
    ).get_data_frames()[0]

    stats = [
        "FGM", "FGA", "FG_PCT", "FG3M", "FG3A", "FG3_PCT", "FTM", "FTA", "FT_PCT", 
        "OREB", "DREB", "REB", "AST", "STL", "BLK", "TOV", "PF", "PTS", "PLUS_MINUS"
    ]

    teams[stats] = (teams.groupby("TEAM_ID")[stats].transform(lambda s: s.rolling(prev_games).mean()))
    teams = teams.rename(columns={s: f"{prev_games}_game_roll_avg_{s}" for s in stats})
    teams = teams.drop(columns=["MIN", "VIDEO_AVAILABLE"])

    return teams.dropna(subset=[f"{prev_games}_game_roll_avg_{s}" for s in stats])

In [9]:
test1 = rolling_avg_team_box_score_stats(SEASON, prev_games=3)
test1

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,3_game_roll_avg_FGM,3_game_roll_avg_FGA,3_game_roll_avg_FG_PCT,3_game_roll_avg_FG3M,3_game_roll_avg_FG3A,3_game_roll_avg_FG3_PCT,3_game_roll_avg_FTM,3_game_roll_avg_FTA,3_game_roll_avg_FT_PCT,3_game_roll_avg_OREB,3_game_roll_avg_DREB,3_game_roll_avg_REB,3_game_roll_avg_AST,3_game_roll_avg_STL,3_game_roll_avg_BLK,3_game_roll_avg_TOV,3_game_roll_avg_PF,3_game_roll_avg_PTS,3_game_roll_avg_PLUS_MINUS
46,22025,1610612744,GSW,Golden State Warriors,0022500097,2025-10-24,GSW @ POR,L,41.000000,85.666667,0.476667,17.000000,41.666667,0.409667,26.000000,31.000000,0.834333,10.333333,31.000000,41.333333,28.666667,11.000000,3.333333,17.666667,21.666667,125.000000,-1.333333
56,22025,1610612753,ORL,Orlando Magic,0022500100,2025-10-25,ORL vs. CHI,L,37.666667,85.000000,0.444000,8.000000,28.333333,0.271667,26.666667,35.000000,0.765333,12.000000,36.000000,48.000000,18.666667,7.666667,5.000000,19.000000,23.666667,110.000000,-4.000000
59,22025,1610612737,ATL,Atlanta Hawks,0022500101,2025-10-25,ATL vs. OKC,L,38.000000,86.666667,0.438667,11.333333,34.333333,0.324000,22.333333,28.666667,0.760667,10.666667,29.333333,40.000000,25.333333,7.666667,5.333333,16.333333,22.666667,109.666667,-11.000000
62,22025,1610612756,PHX,Phoenix Suns,0022500104,2025-10-25,PHX @ DEN,L,40.000000,91.000000,0.439000,14.333333,43.666667,0.324667,16.666667,21.666667,0.777333,15.000000,27.000000,42.000000,23.333333,8.666667,5.000000,18.000000,26.333333,111.000000,-15.000000
63,22025,1610612760,OKC,Oklahoma City Thunder,0022500101,2025-10-25,OKC @ ATL,W,44.000000,97.333333,0.452333,12.333333,41.333333,0.304667,27.333333,31.666667,0.859000,11.666667,37.666667,49.333333,22.333333,10.333333,3.000000,13.000000,26.333333,127.666667,8.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,22025,1610612762,UTA,Utah Jazz,0022501198,2026-04-12,UTA @ LAL,L,52.000000,102.666667,0.503333,10.666667,33.666667,0.316000,15.666667,22.666667,0.671000,13.000000,36.000000,49.000000,35.333333,13.666667,3.333333,16.000000,13.666667,130.333333,1.000000
2456,22025,1610612763,MEM,Memphis Grizzlies,0022501194,2026-04-12,MEM @ HOU,L,40.666667,98.666667,0.414667,14.333333,50.333333,0.285667,11.333333,14.000000,0.861667,9.000000,31.666667,40.666667,24.666667,7.666667,3.000000,13.000000,19.666667,107.000000,-31.333333
2457,22025,1610612764,WAS,Washington Wizards,0022501187,2026-04-12,WAS @ CLE,L,42.000000,92.666667,0.454333,14.000000,36.666667,0.384667,16.000000,20.000000,0.796667,11.000000,25.333333,36.333333,26.333333,11.000000,4.000000,15.333333,18.666667,114.000000,-15.666667
2458,22025,1610612765,DET,Detroit Pistons,0022501188,2026-04-12,DET @ IND,W,47.666667,87.333333,0.546333,12.666667,30.000000,0.418333,21.333333,26.000000,0.816333,14.333333,33.333333,47.666667,34.000000,11.333333,8.000000,15.000000,19.333333,129.333333,18.666667
2459,22025,1610612766,CHA,Charlotte Hornets,0022501190,2026-04-12,CHA @ NYK,W,37.000000,87.000000,0.425667,16.000000,49.333333,0.323000,14.000000,17.666667,0.786667,13.333333,29.000000,42.333333,22.333333,7.333333,6.000000,15.666667,15.333333,104.000000,-5.000000

In [11]:
test.to_csv("../data/2025_rolling_avg_team_stats.csv", index=False)

### In-Game Data

Fill this out later